routes/web.php
<?php

use App\Article;
use Zahra\Category;
use Zahra\Project;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/typography', function(){
    return view('typography');
});

Route::get('/', 'HomeController@index');


Route::get('/loadMorePortfolio ', function(){
    $categories = Category::get();
    $projects = Project::with('images','categories')->where(['is_featured' => '0', 'is_published' => '1'])->get();
    return view('loadMorePortfolio', compact('projects', 'categories'));
});



Route::post('/image/store', 'ImageController@store')->middleware('auth');
Route::delete('/image/delete/{name}', 'ImageController@destroy')->middleware('auth');

Route::prefix('project')->group(function (){
    Route::get('/', 'ProjectController@index')->middleware('auth')->name('projects');
    Route::post('patch/{id}', 'ProjectController@update')->middleware('auth');
    Route::get('create', 'ProjectController@create')->middleware('auth');
    Route::get('edit/{id}', 'ProjectController@edit')->middleware('auth');
    Route::post('store', 'ProjectController@store')->middleware('auth');
    Route::get('{id}', 'ProjectController@show');
    Route::delete('delete/{id}', 'ProjectController@destroy')->middleware('auth');
    Route::patch('toggleState/{id}', 'ProjectController@toggleState')->middleware('auth');
    Route::patch('toggleFeaturedState/{id}', 'ProjectController@toggleFeaturedState')->middleware('auth');
});


Auth::routes();

Route::prefix('admin')->group(function(){
    Route::get('/', 'ProjectController@index')->middleware('auth')->name('projects');
});

Route::prefix('category')->group(function(){
    Route::get('/', 'CategoryController@index')->middleware('auth');
    Route::get('/create', 'CategoryController@create')->middleware('auth');
    Route::get('edit/{id}', 'CategoryController@edit')->middleware('auth');
    Route::post('update/{id}', 'CategoryController@update')->middleware('auth');
    Route::post('store', 'CategoryController@store')->middleware('auth');
    Route::delete('delete/{id}', 'CategoryController@destroy')->middleware('auth');
});

Route::prefix('profile')->group(function () {
    Route::get('/', 'ProfileController@index')->middleware('auth');
    Route::get('/edit/', 'ProfileController@edit')->middleware('auth');
    Route::post('/update/', 'ProfileController@update')->middleware('auth');
    Route::get('/about-me', 'ProfileController@show');
    Route::get('/skills', 'SkillController@index')->middleware('auth');
    Route::get('/skills/create', 'SkillController@create')->middleware('auth');
    Route::post('/skills/store', 'SkillController@store')->middleware('auth');
    Route::delete('/skills/delete/{id}', 'SkillController@destroy')->middleware('auth');
    Route::get('/skills/edit/{id}', 'SkillController@edit')->middleware('auth');
    Route::patch('/skills/update/{id}', 'SkillController@update')->middleware('auth');
});

Route::prefix('setting')->group( function () {
    Route::get('/', 'SettingController@index')->middleware('auth');
    Route::patch('/social_link/update', 'SettingController@update_social_link')->middleware('auth');
    Route::get('/social_link/edit', 'SettingController@edit_social_link')->middleware('auth');
    Route::get('site_settings/edit', 'SettingController@edit_site_settings')->middleware('auth');
    Route::patch('site_settings/update', 'SettingController@update_site_settings')->middleware('auth');
    Route::post('/logo', 'SettingController@store_logo')->middleware('auth');
    Route::get('/logo/edit', 'SettingController@edit_logo')->middleware('auth');
});

app/Category.php
<?php

namespace Zahra;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    public function projects(){
        return $this->belongsToMany('Zahra\Project');
    }

    public function categories(){
        return $this->belongsToMany('Zahra\Project');
    }

    public function number_of_projects(){
        return $this->belongsToMany('Zahra\Project');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace Zahra\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Zahra\Category;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $categories = Category::orderBy('id', 'desc')->withCount('number_of_projects')->get();
        // return $categories;

        if ($request->ajax()) {
            return response()->json($categories)->header('Vary', 'Accept');;
        }

        return view('backend.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $category = new Category;
        $category->name = $request->name;
        $category->save();
        return redirect('/category')->with('status', 'Category created!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::find($id);
        return view('backend.categories.edit', compact('category'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = Category::find($id);
        $category->name = $request->name;
        $category->save();
        return redirect('category')->with('status', 'Category name updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::with('projects')->where('id', $id)->first();
        if($category->projects->count()){
            return redirect('/category')->with('deleted', 'Category cannot be deleted! This category has projects assigned to them. Please remove the projects first or change their category.');
        }

        if($category->count() < 2){
            return redirect('/category')->with('deleted', 'Category cannot be deleted! There at least needs to be one category');
        }
        $category->delete();
        return redirect('/category')->with('deleted', 'Category deleted!');
    }
}

resources/views/backend/categories/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Create new category</div>
                    <div class="card-body">
                        <form method="post" action="/category/store">
                            {{csrf_field()}}
                            <div class="form-group">
                                <label for="usr">Name:</label>
                                <input type="text" class="form-control" name="name" id="category">
                            </div>
                          <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/backend/categories/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Edit category</div>
                    <div class="card-body">
                        <form method="post" action="/category/update/{{$category->id}}">
                            {{csrf_field()}}
                            <div class="form-group">
                                <label for="usr">Name:</label>
                                <input type="text" class="form-control" name="name" id="category" value="{{$category->name}}">
                            </div>
                          <button type="submit" class="btn btn-primary">Update</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/backend/categories/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Categories</div>

                <div class="card-body" id="vue-app">

                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    @if (session('deleted'))
                        <div class="alert alert-danger">
                            {{ session('deleted') }}
                        </div>
                    @endif

                    <table  class="table">
                        <thead>
                          <tr>
                            <th>Name</th>
                            <th>Projects</th>
                            <th></th>
                          </tr>
                        </thead>
                        <tbody>
                            @foreach($categories as $category)
                                <tr>
                                    <td>
                                        {{ $category->name }}
                                    </td>
                                    <td>{{ $category->number_of_projects_count }}</td>
                                    <td>
                                        <div class="float-right">
                                            <div class="btn-group" role="group">
                                              <a class="btn btn-light" href="/category/edit/{{ $category->id }}">
                                                  <i class="material-icons">edit</i>
                                              </a>
                                              <button type="button" class="btn btn-light dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                <span class="sr-only">Toggle Dropdown</span>
                                              </button>
                                              <div class="dropdown-menu">
                                                <form method="POST" action="/category/delete/{{$category->id}}">
                                                    @csrf
                                                    @method('DELETE')
                                                    <button class="dropdown-item btn btn-light">Delete</button>
                                                </form>
                                              </div>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>

                </div>

                <div class="card-footer">
                    <a href="/category/create" class="btn btn-primary">New Category</a>
                </div>
            </div>
        </div>
    </div>


</div>
@endsection